-- ====================================================
-- منصة وتطبيق الحكيم - SUPABASE DATABASE SCHEMA (FULL SYNC)
-- ====================================================

-- 1. جدول الأطباء (doctors)
CREATE TABLE IF NOT EXISTS doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    specialty TEXT NOT NULL,
    title TEXT,
    city TEXT NOT NULL,
    address TEXT,
    price NUMERIC NOT NULL DEFAULT 3000,
    currency TEXT DEFAULT 'د.ج',
    experience_years INT DEFAULT 5,
    phone TEXT,
    working_hours TEXT,
    bio TEXT,
    rating NUMERIC DEFAULT 5.0,
    reviews_count INT DEFAULT 0,
    gender TEXT DEFAULT 'male',
    avatar_bg TEXT DEFAULT '#e0f2fe',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. جدول آراء وتقييمات المرضى (reviews)
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id BIGINT REFERENCES doctors(id) ON DELETE CASCADE,
    author TEXT NOT NULL,
    stars INT CHECK (stars >= 1 AND stars <= 5),
    comment TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. جدول المواعيد والحجوزات والإلغاء (appointments)
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id BIGINT REFERENCES doctors(id) ON DELETE CASCADE,
    patient_name TEXT NOT NULL,
    patient_phone TEXT NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time TEXT NOT NULL,
    notes TEXT,
    status TEXT DEFAULT 'مؤكد', -- مؤكد / ملغى
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- تفعيل سياسات الوصول (RLS) القراءة، الإضافة، التحديث، والإلغاء
ALTER TABLE doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read doctors" ON doctors FOR SELECT USING (true);
CREATE POLICY "Allow public insert doctors" ON doctors FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read reviews" ON reviews FOR SELECT USING (true);
CREATE POLICY "Allow public insert reviews" ON reviews FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read appointments" ON appointments FOR SELECT USING (true);
CREATE POLICY "Allow public insert appointments" ON appointments FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update appointments" ON appointments FOR UPDATE USING (true);
CREATE POLICY "Allow public delete appointments" ON appointments FOR DELETE USING (true);

-- بيانات أولية للأطباء
INSERT INTO doctors (name, specialty, title, city, address, price, currency, experience_years, phone, working_hours, bio, rating, reviews_count, gender, avatar_bg)
VALUES 
('د. عبد الرزاق بن علي', 'جراحة العظام', 'أخصائي جراحة العظام والمفاصل والعمود الفقري', 'الجزائر العاصمة', 'حي حيدرة - شارع القدس', 3500, 'د.ج', 16, '+213 551 23 45 67', 'السبت إلى الأربعاء (09:00 ص - 04:30 م)', 'خريج كلية الطب بالجزائر، خبرة 16 سنة في جراحة المفاصل.', 4.9, 38, 'male', '#e0f2fe'),
('د. سارة بلقاسم', 'الأمراض الجلدية', 'أخصائية الأمراض الجلدية والتجميل والعلاج بالليزر', 'وهران', 'حي العقيد لطفي', 3000, 'د.ج', 11, '+213 552 98 76 54', 'الأحد إلى الخميس (10:00 ص - 05:00 م)', 'متخصصة في العلاجات الجلدية المتطورة والتجميل غير الجراحي.', 4.8, 52, 'female', '#fce7f3'),
('د. يوسف التلمساني', 'أمراض القلب', 'استشاري أمراض القلب وقسطرة الشرايين', 'قسنطينة', 'حي سيدي مبروك', 4500, 'د.ج', 20, '+213 553 44 55 66', 'السبت إلى الخميس (08:30 ص - 03:00 م)', 'أستاذ مبرز في أمراض القلب وتخطيط صمامات القلب.', 5.0, 64, 'male', '#dcfce7');
